# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalgame-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: portalgame-container
        image: ernestogs/portalgame:web3
        ports:
        - containerPort: 443
        env:
        - name: MONGODB_URI
          value: "mongodb://192.168.1.16:27017"
